title: Bienvenido al blog de Daniel Magaña Pérez
email: danielmp01189@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Bienvenidos al blog de Daniel Magaña, aquí encontraras algunas prácticas que 
  hemos realizado en la asignatura de iaw
baseurl: "" # the subpath of your site, e.g. /blog
url: "Daniel-Magana512@github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: danielmagana
github_username:  Daniel-Magana512

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

